eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      defaultZone: http://192.168.11.1:8761/eureka/,http://192.168.21.1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000