customer:
  security:
    authentication:
      oauth:
        client: run-client
        secret: run-secret-token-in-prod
        token-validity-in-seconds: 86400
        refresh-token-validity-in-seconds: 2592000

spring:
  redis:
    database: 0
    host: r-uf640df4b9fb93f4.redis.rds.aliyuncs.com
    port: 6379
    password: ruihu@run-321
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  resources:
    add-mappings: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.11.1:8761/eureka/,http://192.168.21.1:8761/eureka/
  instance:
    prefer-ip-address: true