server:
  port: 18081
  tomcat:
    max-connections: 1000
    max-threads: 500
  connection-timeout: 60000

hystrix:
  command:
    default:
      coreSize: 100
      maximumSize: 1000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

spring:
  application:
    name: run-common
  profiles:
    active: dev

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.rzlearn.common.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    #capital-mode: true
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false